### PR TITLE
Added support for indexing like an array and const functions.

### PR DESCRIPTION
**Pull request by finitespace**

### CODE REVIEW

**Comment by ivanseidel** [comment]
Hi @finitespace, can you explain more about the improvements?

**Comment by finitespace** [comment]
Yes, you can treat the linked list like an array. For example:

int myvalue = myLinkList[0];

Constant functions are required for this type of indexing.

**Comment by ivanseidel** [comment]
Now I get it.
However, the iterator method has been copied. Make a call for the original one from the new one, so that we can simplify the code as much as we can please

**Comment by finitespace** [comment]
Unfortunately that is not possible.

It was copied because it must be a constant function. You cannot call a non constant function from a constant function.

**Comment by ivanseidel** [comment]
Thanks for the PR! This is now in production

**Pull request closed without merging**
